### PR TITLE
Open README.rst as utf-8

### PR DESCRIPTION
**Pull request by cmarqu**
The README seems to have gotten non-ASCII characters (an en-dash at least).

### CODE REVIEW

**Comment by cmarqu** [comment]
Should prevent the error
```
File "/tools/cocotbext-wishbone/setup.py", line 4, in
long_description = fh.read()
File "/opt/rh/rh-python36/root/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1370: ordinal not in range(128)
```

**Comment by wallento** [comment]
Actually, pypi did not like that. Instead I removed the character, a non-ascii hyphen. It now published from the github action from the 0.2 tag after release. From now on all maintainers can release by creating a github release!

**Comment by wallento** [comment]
https://github.com/wallento/cocotbext-wishbone/commit/7abb5c681cf93baca17acd2c5132d9d902fe25aa

**Comment by wallento** [comment]
Okay, I am dying. Let me give it another try..

**Comment by wallento** [comment]
I have no idea what is going on. Twine doesn't even like most simple rst, I can run check locally and it complains about syntax errors about a file with the title only..

**Comment by wallento** [comment]
Just adding it in setup.py:
```py
long_description = """
Test
"""
```
works
```py
long_description = """
Test
====
"""
```
doesn't..

**Comment by cmarqu** [comment]
Add ``long_description_content_type = "text/x-rst"``?
Gotten from https://packaging.python.org/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata

**Comment by wallento** [comment]
Doesn't work. It even says it takes it as default
```
  `long_description` has syntax errors in markup and would not be rendered on PyPI.
  warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
```

**Comment by wallento** [comment]
```py
    long_description="""
Test
====
    """,
```
errors:
```
  `long_description` has syntax errors in markup and would not be rendered on PyPI.
```
Giving up for today, need some distance ;)

**Comment by cmarqu** [comment]
CR/LF problem, as in https://github.com/pypa/twine/issues/495?

**Comment by wallento** [comment]
they are LF, is that the bad one? ;)

**Comment by cmarqu** [comment]
Line ending just may not be mixed. Is ``file README.rst`` okay with it?
It must be something simple like that... :/

**Pull request merged**
